# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0f3e79938628c542f69c9897fc447773db498cb13f85e14953ded8f84df17ec13a91014ef6782b0dbb4749bfb475d8e864e329a9aff3fca3d099db8f8bba96d

test:
  secret_key_base: 8829386832f94c9d6248fb4015d4a8d2b415e34fa9027f818ccaf3b066fa5a38645047acca666f08764f1739ffc52b74effef0262d8ac7759719015bf4a94dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
